//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietHoaDon
    {
        public int maCTHD { get; set; }
        public System.DateTime NgayMua { get; set; }
        public string SDTKH { get; set; }
        public string DCGiaoHang { get; set; }
        public double TongTien { get; set; }
        public string DVT { get; set; }
        public double TienGiam { get; set; }
        public string TrangThaiDH { get; set; }
        public string tgGiaoHang { get; set; }
        public double PhiVanChuyen { get; set; }
        public int maSP { get; set; }
        public int maHoaDon { get; set; }
    
        public virtual HoaDon HoaDon { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
