//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BanGiay.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;

    public partial class SanPham
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SanPham()
        {
            this.ChiTietHoaDons = new HashSet<ChiTietHoaDon>();
            this.HoaDons = new HashSet<HoaDon>();
            this.SPYeuThiches = new HashSet<SPYeuThich>();
        }
        public HttpPostedFileBase UploadImage { get; set; }    
        public string maSP { get; set; }
        public string TinhTrangSP { get; set; }
        public string MauSac { get; set; }
        public string HinhAnh1 { get; set; }
        public string MoTaSP { get; set; }
        public double GiaGoc { get; set; }
        public int SLBan { get; set; }
        public string HinhAnh2 { get; set; }
        public string HinhAnh3 { get; set; }
        public string HinhAnh4 { get; set; }
        public double GiaGiam { get; set; }
        public string MaTH { get; set; }
        public string CatID { get; set; }
        public string maDanhgia { get; set; }
        public string maSize { get; set; }
    
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietHoaDon> ChiTietHoaDons { get; set; }
        public virtual DanhGia DanhGia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KichCo KichCo { get; set; }
        public virtual ThuongHieuSP ThuongHieuSP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SPYeuThich> SPYeuThiches { get; set; }
    }
}
